name: Vanessuca
favicon: null
layout_spectrum: 0.11068214825354517
typography_spectrum: 0.3588200316298753
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5737578587140888
  lightness: 0.15572770172730088
  saturation: 0.5574034547898918
  rhythmicContrast: 0.1999319854658097
purpose: []
